name: tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.5
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: key-0
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - run: python -m pip install pre-commit poetry
      - run: pre-commit run --all-files

  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-matrix: ${{ steps.get-python-versions-action.outputs.latest-python-versions }}
    steps:
      - uses: snok/latest-python-versions@v1
        id: get-python-versions-action
        with:
          min-version: 3.8
          include-prereleases: true

  test:
    needs: [ get-python-versions ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{ fromJson(needs.get-python-versions.outputs.python-matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/cache@v2
        with:
          path: ~/.local
          key: ${{ matrix.python-version }}-1
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true
      - uses: actions/cache@v2
        id: cache-venv
        with:
          path: .venv
          key: ${{ hashFiles('**/poetry.lock') }}-${{ matrix.python-version }}-1
      - run: poetry install --no-interaction --no-root --extras all
        if: steps.cache-venv.outputs.cache-hit != 'true'
      - run: poetry install --no-interaction
      - name: Run tests
        run: |
          source .venv/bin/activate
          poetry run pytest --cov-report=xml
          poetry run coverage report
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml
          fail_ci_if_error: true
